apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: photoresizer
  namespace: nginx-mra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-mra
        component: photoresizer
    spec:
      imagePullSecrets:
        - name: <DOCKER_SECRET>
      containers:
      - name: photoresizer
        image: <IMAGE_REPO_AND_TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
        env:
          - name: AWS_ACCESS_KEY_ID
            value: <AWS_ACCESS_KEY_ID>
          - name: AWS_REGION
            value: us-west-1
          - name: AWS_SECRET_ACCESS_KEY
            value: <AWS_SECRET_ACCESS_KEY>
          - name: REDIS_CACHE_URL
            value: "redis.nginx-mra.svc.cluster.local"
          - name: REDIS_CACHE_PORT
            value: "6379"
          - name: S3_BUCKET
            value: <S3_BUCKET>
          - name: S3_URL
            value: <S3_URL>
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /status
            port: 443
            httpHeaders:
              - name: Host
                value: <K8S_HOST_NAME>
          periodSeconds: 20
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 10
