apiVersion: v1
kind: Service
metadata:
  name: photoresizer
  labels:
    app: nginx-mra
    component: photoresizer
  namespace: nginx-mra
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-mra
    component: photoresizer
